services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-gateway
    hostname: pi
    restart: unless-stopped
    network_mode: host 
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /mnt/usb-thumb-drive/server-data/docker-tailscale/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=tskey-auth-AUTH_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=192.168.X.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
